import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

// eslint-config-next ships an eslintrc-style config with no flat entry point, so it comes in
// through FlatCompat — the same bridge create-next-app@15 generates. Scoped to the frontend so
// the backend does not pick up React rules.
const nextConfigs = compat.extends('next/core-web-vitals').map((config) => ({
  ...config,
  files: ['apps/frontend/**/*.{ts,tsx,js,jsx}'],
}));

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      'apps/frontend/graphql/generated/**',
      // Generated by Next on every build and explicitly not to be edited.
      '**/next-env.d.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...nextConfigs,
  {
    // The rule resolves `pages` from the ESLint root, which is the workspace root here.
    files: ['apps/frontend/**/*.{ts,tsx,js,jsx}'],
    rules: {
      '@next/next/no-html-link-for-pages': ['warn', 'apps/frontend/pages'],
    },
  },
  prettier,
);
